var number = prompt("Введите количество ворон");
switch (number) {
	case "1": // if (number === 1)
		document.write("На ветке сидит 1 ворона."); // тогда выводим...
	break
	case "2": // if (number === 2)
		document.write("На ветке сидит 2 вороны."); // тогда выводим...
	break
	case "3": // if (number === 3)
		document.write("На ветке сидит 3 вороны."); // тогда выводим...
	break
	case "4": // if (number === 4)
		document.write("На ветке сидит 4 вороны."); // тогда выводим...
	break
	case "5": // if (number === 5)
		document.write("На ветке сидит 5 ворон."); // тогда выводим...
	break
	case "6": // if (number === 6)
		document.write("На ветке сидит 6 ворон."); // тогда выводим...
	break
	case "7": // if (number === 7)
		document.write("На ветке сидит 7 ворон."); // тогда выводим...
	break
	case "8": // if (number === 8)
		document.write("На ветке сидит 8 ворон."); // тогда выводим...
	break
	case "9": // if (number === 9)
		document.write("На ветке сидит 9 ворон."); // тогда выводим...
	break
	case "10": // if (number === 10)
		document.write("На ветке сидит 10 ворон."); // тогда выводим...
	break
	default: //else
		document.write("Вы ввели кол-во больше 10"); // иначе выводим...
}